### PR TITLE
Python3 and config

### PR DESCRIPTION
**Pull request by tristanlatr**
Hello, 

Major changes:
- Python 3 compatible
- URL and mail server option are configurable from config file to allow several different configurations

Thanks !

### CODE REVIEW

**Review by bth5032 — APPROVED** [review]
Hey thanks, this all looks good. Appreciate the updates! Did you notice that 1 to 10 minutes was enough to get craiglslist to not ban your IP?

**Comment by tristanlatr** [comment]
What kind of error do we get when craigslist banned an iP?

I've setted up this time only to be more reactive.
Personally,  ide rather configure this script with crontab. 

I might submit a new pr in the next days with this arrangements.

**Comment by bth5032** [comment]
The page you load from CL will not be search results anymore. I don't recall exactly what happens, I think the parsing with bs4 fails and you get a crash. But it's been a while since I've tested.

**Comment by tristanlatr** [comment]
Thanks,
I'll update you if I run into any trouble regarding ip ban. There is this always tor to bypass ip ban https://medium.com/the-sysadmin/using-tor-for-your-shell-script-fee9d8bdef5c but might be overkill

**Pull request merged**
